language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  
script:
    # Check the source code for obvious errors
    - python3 -m flake8 . --count --show-source --statistics --select=E901,E999,F821,F822,F823
