language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pyfaidx
  - pip install pysam
  - pip install numpy
  - pip install scikit-bio
script:
    # Check the source code for obvious errors
    - python3 ScanITD.py -h
